// models/productsData.js
// Fuente de datos de los productos de la pastelería Lune.

export const productsData = [
  // ─── POSTRES ──────────────────────────────────────────────
  {
    id: 1,
    nombre: 'Ciudad Blanca',
    precio: 16,
    imagen: '/Postres/CiudadBlanca2.jpeg',
    categoria: 'postres',
    descripcion: 'Coco / Vainilla Amazónica / Papaya arequipeña.',
    disponible: true,
    destacado: true,
  },
  {
    id: 2,
    nombre: 'Entremet de Chocolate',
    precio: 17,
    imagen: '/Postres/Entremet.jpeg',
    categoria: 'postres',
    descripcion: 'Chocolate 79% / Frutos rojos / Jamaica.',
    disponible: true,
    destacado: true,
  },
  {
    id: 3,
    nombre: 'Sacher de Tumbo y Hierba Luisa',
    precio: 16,
    imagen: '/Postres/SacherDeTumbo.jpeg',
    categoria: 'postres',
    descripcion: 'Tumbo / Hierba luisa / Chocolate 79%.',
    disponible: true,
    destacado: false,
  },
  {
    id: 4,
    nombre: 'Amor Eterno',
    precio: 16,
    imagen: '/Postres/AmorEterno.jpeg',
    categoria: 'postres',
    descripcion: 'Baileys / Café / Almendra.',
    disponible: true,
    destacado: false,
  },
  {
    id: 5,
    nombre: 'Charlotte de Lúcuma',
    precio: 16,
    imagen: '/Postres/CharlotteDeLúcuma.jpeg',
    categoria: 'postres',
    descripcion: 'Lúcuma / Chocolate 45% / Cacao.',
    disponible: true,
    destacado: false,
  },
  {
    id: 6,
    nombre: 'Pastel de Queso Japonés',
    precio: 14,
    imagen: null,
    categoria: 'postres',
    descripcion: 'Queso philadelphia / Vainilla Bourbon.',
    disponible: false,
    destacado: false,
  },
  {
    id: 7,
    nombre: 'Choux de Maracuyá',
    precio: 14,
    imagen: null,
    categoria: 'postres',
    descripcion: 'Vainilla / Maracuyá / Chocolate blanco 25%.',
    disponible: true,
    destacado: false,
  },
  {
    id: 8,
    nombre: 'Choux de Café',
    precio: 14,
    imagen: null,
    categoria: 'postres',
    descripcion: 'Cacao / Café Jaén / Chocolate 45%.',
    disponible: true,
    destacado: false,
  },
  {
    id: 9,
    nombre: 'Tartaleta de Toffe',
    precio: 15,
    imagen: null,
    categoria: 'postres',
    descripcion: 'Avellanas / Toffe / Sal de Maras / Manzana.',
    disponible: true,
    destacado: false,
  },
  {
    id: 10,
    nombre: 'Tiramisú',
    precio: 17,
    imagen: null,
    categoria: 'postres',
    descripcion: 'Mascarpone / Licor de café / Cacao / Café.',
    disponible: true,
    destacado: false,
  },
  {
    id: 11,
    nombre: 'Tartaleta de Limón',
    precio: 14,
    imagen: null,
    categoria: 'postres',
    descripcion: 'Limón / Merengue / Avellana.',
    disponible: true,
    destacado: false,
  },
  {
    id: 12,
    nombre: 'Vainilla Cacao',
    precio: 15,
    imagen: null,
    categoria: 'postres',
    descripcion: 'Cacao / Vainilla Amazónica / Chocolate 45%.',
    disponible: true,
    destacado: false,
  },
  {
    id: 13,
    nombre: 'Flor Andina',
    precio: 16,
    imagen: '/Postres/FlorAndina.jpeg',
    categoria: 'postres',
    descripcion: 'Muña / Maíz cabanita / Aguaymanto.',
    disponible: true,
    destacado: false,
  },
  {
    id: 14,
    nombre: 'Delicia Multifloral',
    precio: 16,
    imagen: '/Postres/DeliciaMultifloral.jpeg',
    categoria: 'postres',
    descripcion: 'Miel / Limón / Vainilla / Hierba Luisa.',
    disponible: false,
    destacado: false,
  },
  {
    id: 15,
    nombre: 'Pistacho Rosé',
    precio: 22,
    imagen: null,
    categoria: 'postres',
    descripcion: 'Pistacho / Frambuesa / Vainilla.',
    disponible: true,
    destacado: false,
  },
  {
    id: 16,
    nombre: 'Coco Mango',
    precio: 18,
    imagen: '/Postres/CocoMango.jpeg',
    categoria: 'postres',
    descripcion: 'Coco / Mango / Chocolate blanco.',
    disponible: true,
    destacado: false,
  },
  {
    id: 17,
    nombre: 'Kaori del Valle',
    precio: 17,
    imagen: null,
    categoria: 'postres',
    descripcion: 'Jazmín / Cedrón / Mandarina.',
    disponible: true,
    destacado: false,
  },
  // ─── ESPECIALES ────────────────────────────────────────────────
  {
    id: 18,
    nombre: 'Integral de Pollo',
    precio: 23,
    imagen: null,
    categoria: 'especiales',
    descripcion: 'Multisemillas de masa madre integral / Pollo desilachado / Tomate cherry / Brotes / Yogurt griego / Palta.',
    disponible: true,
    destacado: true,
  },
  {
    id: 19,
    nombre: 'Tostón de Lomo',
    precio: 25,
    imagen: '/Especiales/TostonDeLomo.png',
    categoria: 'especiales',
    descripcion: 'Pan de masa madre y semillas / Lomo fino / Tomate cherry / Brotes / Chips de papas / Semillas de ajonjolí.',
    disponible: true,
    destacado: false,
  },
  {
    id: 20,
    nombre: 'Baguette en Tres Tiempos',
    precio: 28,
    imagen: null,
    categoria: 'especiales',
    descripcion: 'Baguette de masa madre con trigo andino / Palta y Gravlax de trucha / Jamón, queso Lluta y cebolla caramelada / Capressé andino.',
    disponible: true,
    destacado: false,
  },
  {
    id: 21,
    nombre: 'Campestre Mixto',
    precio: 26,
    imagen: null,
    categoria: 'especiales',
    descripcion: 'Focaccia de masa madre con trigo andino / Jamón ahumado / Queso Lluta / Salsa pesto de la casa.',
    disponible: true,
    destacado: false,
  },
  {
    id: 22,
    nombre: 'Pan Criollo con Churrasco Ahumado',
    precio: 26,
    imagen: null,
    categoria: 'especiales',
    descripcion: 'Focaccia de masa madre con trigo andino / Churrasco de lomo fino / Palta / Lechuga / Tomate cherry.',
    disponible: true,
    destacado: false,
  },
  {
    id: 23,
    nombre: 'Ensala César',
    precio: 22,
    imagen: null,
    categoria: 'especiales',
    descripcion: 'Lechuga / Croúton de masa madre / Pollo salteado / Vinagreta César / Queso parmesano.',
    disponible: true,
    destacado: false,
  },
  {
    id: 24,
    nombre: 'Ensalada Lune',
    precio: 21,
    imagen: null,
    categoria: 'especiales',
    descripcion: 'Mix de lechuga / Almendras Tostadas / Pollo salteado / Vinagreta de la casa / Queso Lluta.',
    disponible: true,
    destacado: false,
  },
  // ─── DESAYUNOS ─────────────────────────────────────────────
  {
    id: 25,
    nombre: 'Desayuno Poché',
    precio: 22,
    imagen: null,
    categoria: 'desayunos',
    descripcion: 'Pan del día de masa madre / Huevos escalfados  / Mix de lechugas / Palta / Brotes / Salsa de la casa.',
    disponible: true,
    destacado: false,
  },
  {
    id: 26,
    nombre: 'Desayuno Lune',
    precio: 25,
    imagen: null,
    categoria: 'desayunos',
    descripcion: 'Omelette de huevo / Pan de semillas tostado / Palta / Tocino / Café americano.',
    disponible: true,
    destacado: true,
  },
  {
    id: 27,
    nombre: 'Tosatada Francesa',
    precio: 23,
    imagen: null,
    categoria: 'desayunos',
    descripcion: 'Pan brioche caramelizado / Diplomat de vainilla / Fruta fresca.',
    disponible: true,
    destacado: false,
  },
  // ─── BOLLERIA ─────────────────────────────────────────────
  {
    id: 28,
    nombre: 'Crossant Clásico',
    precio: 8,
    imagen: null,
    categoria: 'bolleria',
    descripcion: 'Clasico croissant de mantequilla, hojaldrado y aireado.',
    disponible: true,
    destacado: false,
  },
  {
    id: 29,
    nombre: 'Crossaant de Café',
    precio: 12,
    imagen: null,
    categoria: 'bolleria',
    descripcion: 'Clasico croissant de mantequilla, hojaldrado y aireado con pasta de café.',
    disponible: true,
    destacado: false,
  },
  {
    id: 30,
    nombre: 'Croissant de Chocolate',
    precio: 11,
    imagen: null,
    categoria: 'bolleria',
    descripcion: 'Clasico croissant de mantequilla, hojaldrado y aireado con chocolate bitter.',
    disponible: true,
    destacado: false,
  },
  {
    id: 31,
    nombre: 'Croissant de Crema Pastelera',
    precio: 11,
    imagen: null,
    categoria: 'bolleria',
    descripcion: 'Clasico croissant de mantequilla, hojaldrado y aireado con crema pastelera.',
    disponible: true,
    destacado: false,
  },
  {
    id: 32,
    nombre: 'Croissant de Jamón y Queso',
    precio: 13,
    imagen: null,
    categoria: 'bolleria',
    descripcion: 'Clasico croissant de mantequilla, hojaldrado y aireado con jamón y queso.',
    disponible: true,
    destacado: false,
  },
  {
    id: 33,
    nombre: 'Pan de Semillas (1KG)',
    precio: 13,
    imagen: null,
    categoria: 'bolleria',
    descripcion: 'Pan de masa madre / Chía / Linza / 20% Harina integral.',
    disponible: true,
    destacado: false,
  },
  {
    id: 34,
    nombre: 'Focaccia (125 G.)',
    precio: 2.50,
    imagen: null,
    categoria: 'bolleria',
    descripcion: 'Pan de masa madre / Aceite de oliva extra virgen / Sal de maras.',
    disponible: true,
    destacado: false,
  },
  {
    id: 35,
    nombre: 'Baguette (300 G.)',
    precio: 3.50,
    imagen: null,
    categoria: 'bolleria',
    descripcion: 'Pan de masa madre / Sal de maras.',
    disponible: true,
    destacado: false,
  },
  // ─── BEBDIAS FRIAS ─────────────────────────────────────────────
  {
    id: 36,
    nombre: 'Frapuccino',
    precio: 14,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: false,
  },
  {
    id: 37,
    nombre: 'Frapmocaccino',
    precio: 15,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 38,
    nombre: 'Frappe de Matcha',
    precio: 17,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 39,
    nombre: 'Frappe de Chocolúcuma',
    precio: 16,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 40,
    nombre: 'Frappe de Algarrobina',
    precio: 16,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 41,
    nombre: 'Frappe de Fresa',
    precio: 16,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 42,
    nombre: 'Frappe de Mango y Maracuya',
    precio: 15,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 43,
    nombre: 'Frappe de Carameltoffe',
    precio: 16,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 44,
    nombre: 'Agua con Gas / sin Gas',
    precio: 5,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 45,
    nombre: 'Ice Coffe Latte',
    precio: 16,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 46,
    nombre: 'Ice Mocaccino Latte',
    precio: 17,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 47,
    nombre: 'Ice Tres Leches Kafa',
    precio: 18,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 48,
    nombre: 'Ice Caramel Latte',
    precio: 16,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 49,
    nombre: 'Ice Cinamon Latte',
    precio: 16,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 50,
    nombre: 'Ice Matcha Latte',
    precio: 17,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 51,
    nombre: 'Ice Tea de la Casa',
    precio: 16,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 52,
    nombre: 'Jugo de Frútos Rojos',
    precio: 17,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 53,
    nombre: 'Jugo de Maracumango',
    precio: 13,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 54,
    nombre: 'Jugo de Temporada',
    precio: 10,
    imagen: null,
    categoria: 'bebidas_frias',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  // ─── COCTELES ─────────────────────────────────────────────
  {
    id: 55,
    nombre: 'Tinto de Verano',
    precio: 20,
    imagen: null,
    categoria: 'cocteles',
    descripcion: 'Vino Borgoña Isabella.',
    disponible: true,
    destacado: true,
  },
  {
    id: 56,
    nombre: 'Sour de Aguaymanto y Muña',
    precio: 22,
    imagen: null,
    categoria: 'cocteles',
    descripcion: 'Pisco Italia / Sirope de muña / Aguaymanto.',
    disponible: true,
    destacado: true,
  },
  {
    id: 57,
    nombre: 'Kafa Martini',
    precio: 23,
    imagen: null,
    categoria: 'cocteles',
    descripcion: 'Licor de café / Espresso / Wisky / Sirope de canela.',
    disponible: true,
    destacado: true,
  },
  {
    id: 58,
    nombre: 'Tropicoqueta',
    precio: 24,
    imagen: null,
    categoria: 'cocteles',
    descripcion: 'Piña / Mango / Maracuyá / Yogurt griego / Pisco.',
    disponible: true,
    destacado: true,
  },
  // ─── KAMBUCHAS ─────────────────────────────────────────────
  {
    id: 59,
    nombre: 'Chill Out',
    precio: 14,
    imagen: null,
    categoria: 'kombuchas',
    descripcion: 'Lavanda / Granadilla.',
    disponible: true,
    destacado: true,
  },
  {
    id: 60,
    nombre: 'Sunset Fizz',
    precio: 14,
    imagen: null,
    categoria: 'kombuchas',
    descripcion: 'Manzana / Clavo de olor / Anís estrella.',
    disponible: true,
    destacado: true,
  },
  {
    id: 61,
    nombre: 'Emoliente',
    precio: 14,
    imagen: null,
    categoria: 'kombuchas',
    descripcion: 'Hierba luisa / Menta / Cola de caballo.',
    disponible: true,
    destacado: true,
  },
  {
    id: 62,
    nombre: 'Detox',
    precio: 14,
    imagen: null,
    categoria: 'kombuchas',
    descripcion: 'Pepino / Menta / Limón.',
    disponible: true,
    destacado: true,
  },
  // ─── BEBIDAS CALIENTES ─────────────────────────────────────────────
  {
    id: 63,
    nombre: 'Espresso',
    precio: 6,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 64,
    nombre: 'Espresso Doble',
    precio: 8,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 65,
    nombre: 'Macciato o Cortado',
    precio: 8,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 66,
    nombre: 'Capuccino',
    precio: 10,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 67,
    nombre: 'Latte Macciatto',
    precio: 11,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 68,
    nombre: 'Mocaccino',
    precio: 12,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 69,
    nombre: 'Matchaccino',
    precio: 13,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 70,
    nombre: 'Americano',
    precio: 7,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 71,
    nombre: 'Café Bombón',
    precio: 9,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 72,
    nombre: 'Chocolate Caliente',
    precio: 11,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 73,
    nombre: 'Vino Caliente',
    precio: 17,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 74,
    nombre: 'Affogato de Vainilla Thaití',
    precio: 12,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 75,
    nombre: 'Bombón Como Tú',
    precio: 9,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 76,
    nombre: 'Hierbalito de Eucalipto',
    precio: 9,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 77,
    nombre: 'Bella Durmiente',
    precio: 9,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 78,
    nombre: 'Qori',
    precio: 9,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 79,
    nombre: 'Kuyay',
    precio: 9,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  {
    id: 80,
    nombre: 'Taza de Amor',
    precio: 9,
    imagen: null,
    categoria: 'bebidas_calientes',
    descripcion: '.',
    disponible: true,
    destacado: true,
  },
  // ─── TORTAS ───────────────────────────────────────────────
  {
    id: 81,
    nombre: 'Torta de Chocolate Belga',
    precio: 85,
    imagen: null,
    categoria: 'tortas',
    descripcion: 'Húmeda torta de tres pisos con ganache de chocolate belga 70% cacao y decoración artesanal.',
    disponible: true,
    destacado: true,
  },
  {
    id: 82,
    nombre: 'Torta Red Velvet',
    precio: 90,
    imagen: null,
    categoria: 'tortas',
    descripcion: 'Clásica red velvet con frosting de queso crema y capa de bizcocho aterciopelado.',
    disponible: true,
    destacado: true,
  },
  {
    id: 83,
    nombre: 'Torta de Frutos del Bosque',
    precio: 95,
    imagen: null,
    categoria: 'tortas',
    descripcion: 'Bizcocho de vainilla con crema chantilly, fresas, moras y frambuesas frescas.',
    disponible: true,
    destacado: false,
  },
  {
    id: 84,
    nombre: 'Torta de Limón y Merengue',
    precio: 80,
    imagen: null,
    categoria: 'tortas',
    descripcion: 'Tarta de masa sablée, crema de limón artesanal coronada con merengue italiano tostado.',
    disponible: false,
    destacado: false,
  },
]

export default productsData
